Correct libc dependency
unikraft/libuuid pull request #4
Opened 2023-07-25 15:24 UTC by andreittr

Previously libuuid would hard-select libnewlibc as it requires a libc.
This change eases this restriction into a dependency on any libc.

2023-08-06 07:24 UTC, StefanJum requested changes
This looks good @andreittr, please add `Config.uk:`  as the component in the commit message.

2023-08-06 19:45 UTC, RaduNichita approved these changes
All good also from my side. Thanks, @andreittr 

I have no other comment besides what @StefanJum has already said.

Reviewed-by: Radu Nichita <radunichita99@gmail.com>

2023-08-07 15:17 UTC, StefanJum commented
The discussion on [`lib-sqlite/#6`](https://github.com/unikraft/lib-sqlite/pull/6) (on using `depends on` vs throwing an error at build time) also applies here.

2023-08-11 11:13 UTC, StefanJum approved these changes
We can keep the config dependency since it's a simple one, as discussed [here](https://github.com/unikraft/lib-sqlite/pull/6)
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2023-08-11 12:12 UTC, razvand approved these changes
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2023-08-11 12:21 UTC, closed without merging