Makefile.uk: Restrict private headers to -iquote
unikraft/libuuid pull request #6
Opened 2023-08-29 14:10 UTC by andreittr

All of libuuid's private headers are included using quotes. This change therefore restricts the private include path to quote includes only, to avoid inadvertent overinclusion.

2023-09-09 08:54 UTC, StefanJum requested changes
This works fine, but please add the pr description to the commit message.
All good besides that.

2023-09-28 14:54 UTC, StefanJum approved these changes
All good @andreittr, thanks.
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2023-10-10 20:55 UTC, Starnox approved these changes
Nothing to comment, thanks!

Reviewed-by: Eduard-Florin Mihailescu [mihailescu.eduard@gmail.com](mailto:mihailescu.eduard@gmail.com)

2023-10-11 06:34 UTC, razvand approved these changes
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2023-10-11 06:34 UTC, closed without merging